### ISSUE TITLE
Javadoc Kommentare für: User / Login / Spring Security

### ISSUE THREAD

**Issue by LittleBigPlaye** [fh-erfurt/RateYourStuff2.0#106]
Javadoc Kommentare erstelklen für:
- [x] User-Controller
- [x] User-Models
- [x] User-Exceptions
- [x] User-Dtos
- [x] User-Services

- [x] Login - Models
- [x] Login-Controller
- [x] Login-Exceptions
- [x] Login-Dtos
- [x] Login-Services

- [x] Spring Security-Configs
- [x] Spring Security-Services
- [x] Spring Security-Controller

- [x] Sonstige von @TheBirdEffect erstellte / genutzte Klassen

**Comment by TheBirdEffect** [comment]
JavaDocs finally completed
code cleaning completed
