### ISSUE TITLE
weiterleitung von Episodendetailansicht zum Episodenbearbeitungsformular schlägt fehl mit der folgenden Fehlermeldung 

### ISSUE THREAD

**Issue by MKnop2** [fh-erfurt/RateYourStuff2.0#119]
![bug4](https://user-images.githubusercontent.com/56631092/130061135-29800e9a-fd5f-457b-9bbf-9e3c8b8af079.png)

**Comment by LittleBigPlaye** [comment]
Problem gelöst - TT kann geschlossen werden
