### ISSUE TITLE
Component leftNavigation 

### ISSUE THREAD

**Issue by MKnop2** [fh-erfurt/RateYourStuff2.0#30]
[ ] Navigationsliste als Component erstellen
 [ ] Inhalte anzeigen lassen
 [ ] über toggle in header minimieren und "maximieren"
 [ ] Verlinkung auf Inhalte vorbereiten

**Comment by Avartos** [comment]
- [ ] Navigationsliste als Component erstellen
- [ ] Inhalte anzeigen lassen
- [ ] über toggle in header minimieren und "maximieren"
- [ ] Verlinkung auf Inhalte vorbereiten
