### ISSUE TITLE
Component Bewertung plus Verknüpfung Backend

### ISSUE THREAD

**Issue by Avartos** [fh-erfurt/RateYourStuff2.0#31]
- [x] Component ertsellen
- [x] Bewertung speichern im Backend
- [x] Bewertungen bearbeiten
- [x] Verhindern, dass User doppelte Bewertungen anlegen
- [x] Bewertungen entfernen
- [ ] Auf Bewertungen reagieren (Optional)

**Comment by LittleBigPlaye** [comment]
Funktionen umgesetzt - TT kann geschlossen werden
