### ISSUE TITLE
Bewertungen unter Medien abrufen und anzeigen

### ISSUE THREAD

**Issue by Avartos** [fh-erfurt/RateYourStuff2.0#32]
- [x] Component Bewertungsliste (toggle -> nur 2 Bewertungen standard anziegen, auf  buttonclick, dann mehr)
- [ ]  ZUSATZ: Filter nach Bewertungszahl
- [x] Component Bewertung erstellen
- [x] Daten aus Backend in die Bewertung laden und Component an die Bewertungsliste übergeben. 

ACHTUNG: Platz für die Bilder berücksichtigen. (Maße folgen)

**Comment by LittleBigPlaye** [comment]
Bewertungen können abgerufen und angezeigt werden - TT kann geschlossen werden
